### ISSUE TITLE
Use django-transkribus package for interacting with Transkribus API

### ISSUE THREAD

**Issue by bejohu** [Transkribus/FamousHands#1]
Consider using [django-transkribus](https://github.com/bejohu/django-transkribus) for interacting with Transkribus API.

Here are is a basic example of how it works:

```python
from transkribus import services

api = services.TranskribusAPI()

api.login(
  username='guest',
  password=1234
)

doc = api.get_doc_by_id(COLL_ID, DOC_ID)

for page in doc.pages:

    most_recent_transcript = page.most_recent_transcript

    for transcript in page.transcripts:
        if transcript.id != most_recent_transcript.id:
            print("Not the most recent transcript:", transkript.url)
```

**Comment by albertgreinoecker** [comment]
thx for your contribution, now transkribus-API is used.
Is there more API-support for fetching user information? In the current solution I parse the user attributes from the response text myself.

**Comment by bejohu** [comment]
Yes, there is. _django-transkribus_ does the parsing for you: 

```python
from tranksribus.services import login

user_info = login(username='guest', password=1234)

gender = user_info['gender']
affiliation = user_info['affiliation']

```

With _django-transkribus_ you could do also something like this in your **views.py**:

```python
from django.http HttpResponse

from transkribus.decorators import login_required

@login_required(login_url='/login/', redirect_field_name='/some-view')
def some_view(request):
    if request.user.info.affiliation == 'Some institution':
       return HttpResponse(status_code=401)
    return HttpResponse(status_code=200)
```

You can access user related info such as gender and affiliation using the user object's _.info_ attribute. The data is provided by Transkribus API and is updated each time the user is logged in. Refer to source code for [details](https://github.com/bejohu/django-transkribus/blob/master/transkribus/models.py#L33).

If your use case requires any additional user related info returned by the API, I can add it for you. Same goes for additional API endpoints. BTW these fields are also available (but currently they are not being stored): first_name, last_name, is_staff, login_time, user-agent, user_id, is_active.

Here is how to set it up:

Add _django-transkribus_ to **INSTALLED_APPS** in **settings.py** like this:

```python

INSTALLED_APPS = [
    ...
    transkribus,
    ....
]
```

Then update the database to create the tables required by _django-transkribus_:

```console
python manage.py makemigrations transkribus
python manage.py migrate
```

Your project can now be configured to use _django-transkribus_ for authenticating users. Just add this to **settings.py**.

```python
AUTHENTICATION_BACKENDS = [
    'transkribus.auth_backends.TranskribusBackend',
]
```

If you would like _django-transkribus_ to handle authentication related tasks for you, e.g. signing users in, logout, etc, add this to your **urls.py**:

```python

...

from django.contrib.auth import views as auth_views

...

urlpatterns = [
    ...
    url(r'^login/$', auth_views.login, name='login', kwargs={'template_name': 'my-app/my-login-template.html', 'redirect_authenticated_user': True, 'extra_context': {'next': '/'}}),
    url(r'^logout/$', auth_views.logout_then_login, name='logout', kwargs={'login_url': '/login/'}),
   ...
]
```
